Kinematics interface with KDL implementation
ros-controls/kinematics_interface pull request #1
Opened 2022-06-15 21:52 UTC by pac48

Add kinematics interface with a KDL implementation

The proposed interface defines 5 public methods: `initialize`, `update_robot_state`, `convert_cartesian_deltas_to_joint_deltas`, `calculate_segment_transform`, and `convert_joint_deltas_to_cartesian_deltas`. These methods are sufficient to do basic end effector Cartesian control, but more methods would be needed if we wanted to also do forward and inverse dynamics.

The KDL implementation assumes a URDF has been loaded to the robot_description parameter.

One potential issue is that Eigen is allocating memory for its operations.

I would appreciate feedback anyone has (design pattern and naming conventions)

2022-06-16 17:59 UTC, dignakov commented
I didn't say anything at the meeting, but I think this package is a great addition.

I do have one question/comment. There is already a place where the joint states are stored. What would be the reason for keeping a second set of state inside the kinematic interface? Could it not be a bit more functional where the joint positions, velocities, etc are passed into the functions?

2022-06-16 18:25 UTC, pac48 commented
> I didn't say anything at the meeting, but I think this package is a great addition.
> 
> I do have one question/comment. There is already a place where the joint states are stored. What would be the reason for keeping a second set of state inside the kinematic interface? Could it not be a bit more functional where the joint positions, velocities, etc are passed into the functions?

That is a good point. If the user is require to pass the robot state in all of the other functions, (`convert_cartesian_deltas_to_joint_deltas`, `calculate_segment_transform`, and `convert_joint_deltas_to_cartesian_deltas`), then `update_robot_state` can be removed completely and the interface is almost stateless. The interface can still be in two state of course: initialized/uninitialized. 

I guess the only real benefit to keeping the robot state internally is that the datatypes are different for each plugin. The values come in as vectors of doubles, but will need be copied to whatever type the kinematics interface uses. I am not sure that really matters that much.

2022-06-19 01:30 UTC, pac48 commented
I updated the interface to be stateless. Now each method requires you pass the joint positions in.

2022-06-28 22:46 UTC, bmagyar requested changes
more to come tomorrow morning

2022-06-28 22:46 UTC, bmagyar commented on kdl_plugin/package.xml
> +  <name>kdl_plugin</name>
I'd suggest renaming this to `kinematics_interface_kdl` for more clarity. The name `kdl_plugin` is waaaay too general

2022-06-28 22:46 UTC, bmagyar commented on kdl_plugin/package.xml
> +  <description>KDL based implementation of ROS2 control kinematics interface</description>
```suggestion
  <description>KDL based implementation of ros2_control kinematics interface</description>
```

2022-06-28 22:46 UTC, bmagyar commented on kdl_plugin/kdl_plugin.xml
> +      KDL plugin for ROS2 control kinematics interface
```suggestion
      KDL plugin for ros2_control kinematics interface
```

2022-07-05 06:32 UTC, bmagyar commented on kinematics_interface/CMakeLists.txt
> +        src/kinematics_interface_base.cpp
am I correct that this file was only created to hack that header file into a library?

cmake has *interface libraries* for that: https://cmake.org/cmake/help/latest/command/add_library.html#interface-libraries

2022-07-05 06:35 UTC, bmagyar requested changes

2022-07-05 06:35 UTC, bmagyar commented on kinematics_interface/src/kinematics_interface_base.cpp
> +    //KinematicsBaseClass::~KinematicsBaseClass(){
please remove

2022-07-05 06:35 UTC, bmagyar commented on kinematics_interface/package.xml
> +  <maintainer email="denis@stogl.de">Denis Štogl</maintainer>
can I sign up for membership here? (I'm already reviewing :D ) 
what's the plan for doing releases?

2022-07-05 06:35 UTC, bmagyar commented on kdl_plugin/package.xml
> +  <license>TODO: License declaration</license>
files say apache 2

2022-07-05 06:36 UTC, bmagyar commented on kdl_plugin/CMakeLists.txt
> +cmake_minimum_required(VERSION 3.8)
the folder name here still needs to be changed from `kdl_plugin`

2022-07-05 12:59 UTC, pac48 commented on kinematics_interface/package.xml
> +  <maintainer email="denis@stogl.de">Denis Štogl</maintainer>
I added you!

2022-07-05 16:41 UTC, bmagyar approved these changes

2022-07-05 16:42 UTC, merged