Fix overriding of install
ros-controls/kinematics_interface pull request #13
Opened 2023-01-25 21:40 UTC by tylerjw

This PR cleans up a few things about the CMake but mostly it applies a fix for this: https://colcon.readthedocs.io/en/released/user/overriding-packages.html#how-to-make-it-easier-for-your-users-to-override

2023-01-25 21:45 UTC, ChrisThrasher approved these changes

2023-01-26 17:34 UTC, destogl requested changes
This is a quite opinionated review. I would like to discuss this here before we continue with other things.

2023-01-26 17:34 UTC, destogl commented on kinematics_interface/CHANGELOG.rst
> -
Not sure why you changed this file? Changelog is usually manged by bloom so I would not change it to not get the process confused.

2023-01-26 17:34 UTC, destogl commented on kinematics_interface/CMakeLists.txt
> +project(kinematics_interface LANGUAGES CXX)
How is this different than the previously used function without the argument? Do we have to take care if there are also python files in the package?

2023-01-26 17:34 UTC, destogl commented on kinematics_interface/CMakeLists.txt
> +find_package(Eigen3 REQUIRED)
I would prefer to keep the loop here. it's easier to use dependencies in that way.

2023-01-26 17:34 UTC, destogl commented on kinematics_interface/CMakeLists.txt
> +  rclcpp_lifecycle::rclcpp_lifecycle
Is this really needed to use the “namespaces” (or whatever is this called in this context)

2023-01-26 17:34 UTC, destogl commented on kinematics_interface/CMakeLists.txt
> +target_compile_features(kinematics_interface INTERFACE cxx_std_17)
Why not set the flag for the whole package instead?

2023-01-26 17:34 UTC, destogl commented on kinematics_interface/CMakeLists.txt
> +  rclcpp_lifecycle
Using variable would shorten this – which is something I like a lot

2023-01-26 17:36 UTC, tylerjw commented on kinematics_interface/CHANGELOG.rst
> -
pre-commit did this

2023-01-26 17:37 UTC, tylerjw commented on kinematics_interface/CMakeLists.txt
> +project(kinematics_interface LANGUAGES CXX)
This speeds up the cmake generation step a bit because it only needs to verify it has a C++ compiler and not a C one (or any other language).

2023-01-26 17:37 UTC, tylerjw commented on kinematics_interface/CMakeLists.txt
> +find_package(Eigen3 REQUIRED)
The loop depends on the list variable `THIS_PACKAGE_INCLUDE_DEPENDS` and this is more declarative in cases where you don't need all of them in the same places.

2023-01-26 17:38 UTC, tylerjw commented on kinematics_interface/CMakeLists.txt
> +target_compile_features(kinematics_interface INTERFACE cxx_std_17)
The per-target settings here what is currently recommended by CMake.

2023-01-26 17:39 UTC, ChrisThrasher commented on kinematics_interface/CMakeLists.txt
> +target_compile_features(kinematics_interface INTERFACE cxx_std_17)
Doing it the global way way means the requirement to use C++17 won't propagate to downstream targets which may end up defaulted to an older version and failing to build. It's required that we have this to ensure the build never fail for such reasons.

2023-01-26 17:40 UTC, tylerjw commented on kinematics_interface/CMakeLists.txt
> +  rclcpp_lifecycle::rclcpp_lifecycle
This links to `<package_name>::<library_name>` instead of to every library in the package. It is technically better because in cases where a package exports multiple libraries, this will be faster to link. I can put it back to the ament command that links libraries in each package if you prefer.

2023-01-26 17:45 UTC, destogl commented on kinematics_interface/CHANGELOG.rst
> -
OK, let's keep it then and see what happens :)

2023-01-26 17:46 UTC, destogl commented on kinematics_interface/CMakeLists.txt
> +project(kinematics_interface LANGUAGES CXX)
Should we use this in general always also on package with python scripts only? Of course there is no compilation of Python, but I would like to understand this. Would we be your recommendation?

2023-01-26 17:48 UTC, tylerjw commented on kinematics_interface/CMakeLists.txt
> +project(kinematics_interface LANGUAGES CXX)
This is just telling cmake what tools it needs to ensure are in the environment for what it is about to do. If you have cmake invoke python (not just copy some python scripts to an install) then maybe you'd put something about python here too.

2023-01-26 17:49 UTC, destogl commented on kinematics_interface/CMakeLists.txt
> +find_package(Eigen3 REQUIRED)
I understand what you mean, but often it's just easier to add all. Is there any advantage to put more specific dependencies on a library if another library in the same package has this dependency – so we need it anyway?

My intention here is to make things shorter and simpler in the files, even if this means “too much information” in certain places.

2023-01-26 17:51 UTC, destogl commented on kinematics_interface/CMakeLists.txt
> +  rclcpp_lifecycle::rclcpp_lifecycle
As mentioned above. The question is how much faster is this. If not significant, I would prefer that we lean toward shorter / simpler CMakeLists. This makes it a bit harder to read, even more precise.

2023-01-26 17:51 UTC, destogl commented on kinematics_interface/CMakeLists.txt
> +target_compile_features(kinematics_interface INTERFACE cxx_std_17)
Thanks for the explanation!

2023-01-26 17:52 UTC, ChrisThrasher commented on kinematics_interface/CMakeLists.txt
> +project(kinematics_interface LANGUAGES CXX)
You would never list Python here. If you need Python you can use `find_package(Python 3 REQUIRED)` to find your installation of Python and use that but it's not a language that CMake natively understands so it won't get listed in the `project` call.

2023-01-26 17:56 UTC, tylerjw commented on kinematics_interface/CMakeLists.txt
> +find_package(Eigen3 REQUIRED)
It allows you to write larger packages with multiple libraries. It is an anti-pattern from ROS that we create a 1:1 mapping from package:library and have so many packages. This just makes the build step arbitrarily more complex, and when people are looking for code they depend on, it is much harder because of all the tiny packages.

2023-01-26 18:07 UTC, tylerjw commented
@destogl I pushed a change restoring the THIS_PACKAGE_INCLUDE_DEPENDS list and using ament_target_dependencies instead of target_link_libraries. Do you prefer it like this?

2023-01-26 18:19 UTC, destogl approved these changes
Yes I like ti very much! Thanks for following up!

Let's wait to see what @bmagyar is thinking about this before going to adjust all other PRs.

2023-01-26 18:19 UTC, destogl commented on kinematics_interface/CMakeLists.txt
> +project(kinematics_interface LANGUAGES CXX)
Great! Thanks for the explanations!

2023-01-26 18:48 UTC, bmagyar approved these changes
This is very neat guys, thanks a lot!

2023-01-26 18:51 UTC, tylerjw commented
I'll fix the format job here too if you want me to.

2023-01-26 19:03 UTC, destogl commented
OK, I merge master here. Now we have very clean PR. If CI is happy I am merging this!

2023-01-26 19:08 UTC, merged