Pass the robot_description as an arg in initialize() with fallback to using node's parameters
ros-controls/kinematics_interface pull request #66
Opened 2024-04-09 17:56 UTC by SyllogismRXS

Per the discussion in the admittance_controller of ros2_controllers (https://github.com/ros-controls/ros2_controllers/pull/1094), pass the robot_description string as an input argument to `initialize()` and fallback to getting the robot_description from the node's parameters.

2024-04-09 18:13 UTC, saikishor requested changes
Hello!

I think it is better to add a completely new `initialize` method that doesn't have the parameter interface but has the robot_description and then reuse it within the other `initialize` method

2024-04-09 18:56 UTC, saikishor commented
> > I think it is better to add a completely new `initialize` method that doesn't have the parameter interface but has the robot_description and then reuse it within the other `initialize` method
> 
> but there are more ROS parameters used with the kdl interface. how would you design the `initialize` method of the base class?

I agree it will be hard in that case?. Either we go with this implementation (or) have a method called `set_robot_description` to set it. Any of this should be fine

2024-04-10 16:57 UTC, christophfroehlich commented
I don't think that there are others than `_kdl` publicly available @pac48?
The interfaces are loaded dynamically by admittance_controller using pluginlib, which means we need a general API for the base class. And I don't think we should start adding a dedicated parameter for `_kdl`. But we could use a parameter map maybe, if we want to remove the node_parameter_interface?

2024-04-10 17:17 UTC, SyllogismRXS commented
Do you have a recommended parameter map implementation or library?

Using a parameter map will have the same potential issues as using the node_parameter_interface. It's not obvious to the user of the kinematics_interface library which parameters need to be present by the plugin that will be loaded. Thus, it seems that adding the robot_description back into the node parameter interface is just like using a separate parameter map interface. It would require the user of the kinematics_interface library to add the robot_description to the node_parameter_interface before calling `initialize()` like I did in the admittance controller.

Let me know what you think and I can make the change.

2024-04-10 18:10 UTC, christophfroehlich commented
> Do you have a recommended parameter map implementation or library?

I thought about a simple unordered_map like we use it [here](https://github.com/ros-controls/ros2_control/blob/master/hardware_interface/include/hardware_interface/hardware_info.hpp#L121-L122).

> Using a parameter map will have the same potential issues as using the node_parameter_interface. It's not obvious to the user of the kinematics_interface library which parameters need to be present by the plugin that will be loaded. Thus, it seems that adding the robot_description back into the node parameter interface is just like using a separate parameter map interface. It would require the user of the kinematics_interface library to add the robot_description to the node_parameter_interface before calling `initialize()` like I did in the admittance controller.

I think that's up for the authors of the respective plugin to document that and give proper warnings if a parameter is not given or not within expected specs. 
I'd give the robot_description explicitly, but I don't have preference between passing additional arguments via node options or any parameter-map. what you think @saikishor ?

2024-04-10 18:16 UTC, christophfroehlich commented
Hm, maybe I was wrong: For example, to make the admittance controller work with different (possibly unknown) kinematics_interfaces, we can't use an unordered map without an additional parser for parameters which aren't known at compile time. So maybe it's cleaner to stay with ROS-parameters.

2024-04-10 18:18 UTC, saikishor commented
I would avoid parameter maps. I think having things explicit makes it easier

2024-04-10 18:23 UTC, christophfroehlich commented
> I would avoid parameter maps. I think having things explicit makes it easier

but how to make things explicit with a dynamically loaded library, where we can't know all parameters when writing the caller (in admittance controller in our example)?

2024-04-10 18:34 UTC, saikishor commented
> but how to make things explicit with a dynamically loaded library, where we can't know all parameters when writing the caller (in admittance controller in our example)?

Sorry for the confusion, as for any kinematic interface it would need the robot description right?, this would be an explicit parameter for me, and all other individual parameters should be taken care of from the parameter interface we provide by those respective derived classes. 

If it's possible, It is better to have another initialize method where the robot description is not the last argument as it is very clear about its importance here. This way we use the old API in the older ROS versions and from rolling on we use the new API and deprecate the other one eventually

2024-07-24 12:57 UTC, destogl requested changes

2024-07-24 12:57 UTC, destogl commented on kinematics_interface/include/kinematics_interface/kinematics_interface.hpp
> +    const std::string & robot_description = "") = 0;
Let's be crazy here and just replace "end_effector_name" with "robot_description".  And make `robot_description` mandatory.

Then we read `end_effector` from the parameters by provided `parameters_interface`.

2024-07-24 15:04 UTC, bmagyar commented on kinematics_interface/include/kinematics_interface/kinematics_interface.hpp
> +    const std::string & robot_description = "") = 0;
I think the word we are looking for is namespace, see below ;) 

```
virtual bool initialize(
    const std::string & robot_description,
    std::shared_ptr<rclcpp::node_interfaces::NodeParametersInterface> parameters_interface,
    const std::string & param_namespace = "kinematics",
    ) = 0;
```

2024-07-24 15:05 UTC, bmagyar approved these changes
In general I like the way this is going.

2024-07-24 15:22 UTC, saikishor commented on kinematics_interface/include/kinematics_interface/kinematics_interface.hpp
> +    const std::string & robot_description = "") = 0;
Yes exactly! This is the right way to do it. I want to avoid making the `robot_description` an optional arg.

2024-08-14 14:10 UTC, destogl commented
Closed in favor of #83.

2024-08-14 14:10 UTC, closed without merging