API changes to support robot description
ros-controls/kinematics_interface pull request #83
Opened 2024-08-14 13:54 UTC by destogl

As discussed in #66. This replaces it.

The Admittance Controller changes are in ros-controls/ros2_controllers#

2024-08-14 14:09 UTC, destogl commented on kinematics_interface_kdl/src/kinematics_interface_kdl.cpp
> +
```suggestion

```

2024-08-14 15:15 UTC, saikishor requested changes
Minor comments
The rest looks great :)
Thanks for the nice work

2024-08-14 15:15 UTC, saikishor commented on kinematics_interface/include/kinematics_interface/kinematics_interface.hpp
> +    const std::string & param_namespace = "kinematics") = 0;
Do we want to hardcode this here?

2024-08-14 15:15 UTC, saikishor commented on kinematics_interface_kdl/src/kinematics_interface_kdl.cpp
> +  if (parameters_interface->has_parameter(param_namespace + "tip"))
```suggestion
  if (parameters_interface->has_parameter(ns + "tip"))
```

2024-08-14 15:15 UTC, saikishor commented on kinematics_interface_kdl/src/kinematics_interface_kdl.cpp
> +  auto end_effector_name = rclcpp::Parameter("tip", "MISSING_END_EFFECTOR_NAME");
```suggestion
  auto end_effector_name = rclcpp::Parameter();
```

Do we need this?
why not add check after the get_parameter and if it is empty, then print error and return false?

`if (!robot_tree.getChain(root_name_, end_effector_name, chain_))`

Here in L81 it expects a string I believe, I'm not sure though. If is it a string, then it needs to be changed

2024-08-16 17:21 UTC, destogl commented on kinematics_interface/include/kinematics_interface/kinematics_interface.hpp
> +    const std::string & param_namespace = "kinematics") = 0;
You are right, we don't need this here:

```suggestion
    const std::string & param_namespace) = 0;
```

2024-08-16 17:22 UTC, destogl commented on kinematics_interface_kdl/include/kinematics_interface_kdl/kinematics_interface_kdl.hpp
> +    const std::string & param_namespace = "kinematics") override;
```suggestion
    const std::string & param_namespace) override;
```

2024-08-19 07:58 UTC, Nibanovic commented on kinematics_interface_kdl/src/kinematics_interface_kdl.cpp
> +  auto end_effector_name = rclcpp::Parameter("tip", "MISSING_END_EFFECTOR_NAME");
We don't, thanks!

Now returning `false` on missing `tip` parameter. Added a small test for this as well.

2024-08-19 12:51 UTC, bmagyar requested changes

2024-08-19 12:51 UTC, bmagyar commented on kinematics_interface/include/kinematics_interface/kinematics_interface.hpp
> +    const std::string & param_namespace) = 0;
if we only introduced a new initialize argument we could put this in humble or that's not an interest?

2024-11-04 12:02 UTC, bmagyar approved these changes

2024-11-04 13:31 UTC, merged