Calculate frame difference
ros-controls/kinematics_interface pull request #93
Opened 2024-11-14 17:21 UTC by francesco-donofrio

This PR introduces a method to compute frame differences, along with a corresponding KDL implementation.

2024-11-14 22:04 UTC, aprotyas commented on kinematics_interface/include/kinematics_interface/kinematics_interface.hpp
> +    std::vector<double> & delta_x_vec);
Why not imbibe the size constraints?

```suggestion
    std::array<double, 7> & x_a_vec, std::array<double, 7> & x_b_vec, double dt,
    std::array<double, 6> & delta_x_vec);
```

2024-11-15 15:27 UTC, francesco-donofrio commented on kinematics_interface/include/kinematics_interface/kinematics_interface.hpp
> +    std::vector<double> & delta_x_vec);
I used `std::vector<double>` to maintain consistency with the `convert_joint_deltas_to_cartesian_deltas` method, where `std::vector<double>` is used for the `delta_x` parameter.

2024-12-21 20:14 UTC, christophfroehlich reviewed
in principle LGTM.
But afaik this is really breaking ABI in the controllers due to the new virtual method. 
Do you need this in Jazzy? We can break Rolling, but want to avoid that on Jazzy. 

We can either add version macros (with rclcpp/version.h for example) to add this only on rolling or create a new branch for jazzy.

2024-12-22 06:08 UTC, francesco-donofrio commented
@christophfroehlich I'm currently using such feature in Humble, into a custom controller.

What do you mean with breaking ABI in the controllers?

2024-12-22 10:38 UTC, christophfroehlich commented
Ok we can't backport this to humble. But you always can compile the rolling development version of the ros2_control stack from source on humble distro.

Disclaimer: I'm not an expert here but from what I learned:
Changing/Adding virual methods changes the vtable layout. Programs statically linking against this library break if not both are updated accordingly. This happens often if users only update the ros2_controllers but don't upgrade the dependencies: Then the system may explode unexpectedly.

2025-01-23 12:32 UTC, christophfroehlich requested changes
I changed my mind regarding ABI break, as @saikishor already said

> I'm not sure about the kinematics interface, because it is plugin based and break in ABI is not a problem mostly, as it is used along with smart pointers. For instance: https://github.com/ros-controls/ros2_controllers/blob/master/admittance_controller%2Finclude%2Fadmittance_controller%2Fadmittance_rule.hpp#L191-L193

I am not allowed to push to your branch, could you please merge the master branch and hopefully the failing clang job is fixed then.

2025-02-21 10:21 UTC, my-rice commented
I merged the master branch on behalf of my colleague @francesco-donofrio, and now the PR for unisa-acg:feature/calculate_frame_difference is up to date with ros-controls:master.

2025-02-21 10:46 UTC, bmagyar commented
A Quick CI run and we'll know more. Thank you for following up @my-rice

2025-02-24 08:35 UTC, christophfroehlich approved these changes
Thanks. 
We see the failing RHEL job also on the master branch, this is not related to this PR.

2025-03-11 21:15 UTC, bmagyar approved these changes
Created a branch for Jazzy. This goes into Rolling and Kilted (soon!)

2025-03-11 21:15 UTC, merged